config/routes.rb
Rails.application.routes.draw do
  resources :camp_instructors
  resources :camps
  resources :curriculums
  resources :locations
  resources :instructors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/curriculum.rb
class Curriculum < ApplicationRecord
    #relationship
    has_many :camps
    
    #validations
    validates :name, presence: true, uniqueness: { case_sensitive: false }
    validates :min_rating, presence: true, numericality: { greater_than_or_equal_to: 0}
    validates :max_rating, presence: true, numericality: { less_than_or_equal_to: 3000}
    
    #scopes 
    scope :active, -> { where(active: true) }
    scope :inactive, -> { where(active: false) }
    scope :alphabetical, -> { order(:name) }
    scope :for_rating, ->(rating) {where(' ? >= min_rating and ? <= max_rating ', rating, rating)} 
    
end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  before_action :set_curriculum, only: [:show, :edit, :update, :destroy]

  # GET /curriculums
  # GET /curriculums.json
  def index
    @curriculums = Curriculum.all
  end

  # GET /curriculums/1
  # GET /curriculums/1.json
  def show
  end

  # GET /curriculums/new
  def new
    @curriculum = Curriculum.new
  end

  # GET /curriculums/1/edit
  def edit
  end

  # POST /curriculums
  # POST /curriculums.json
  def create
    @curriculum = Curriculum.new(curriculum_params)

    respond_to do |format|
      if @curriculum.save
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully created.' }
        format.json { render :show, status: :created, location: @curriculum }
      else
        format.html { render :new }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curriculums/1
  # PATCH/PUT /curriculums/1.json
  def update
    respond_to do |format|
      if @curriculum.update(curriculum_params)
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully updated.' }
        format.json { render :show, status: :ok, location: @curriculum }
      else
        format.html { render :edit }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculums/1
  # DELETE /curriculums/1.json
  def destroy
    @curriculum.destroy
    respond_to do |format|
      format.html { redirect_to curriculums_url, notice: 'Curriculum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculum
      @curriculum = Curriculum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curriculum_params
      params.require(:curriculum).permit(:name, :min_rating, :max_rating, :description, :active)
    end
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/curriculums/_form.html.erb
<%= form_with(model: curriculum, local: true) do |form| %>
  <% if curriculum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curriculum.errors.count, "error") %> prohibited this curriculum from being saved:</h2>

      <ul>
      <% curriculum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :curriculum_name %>
  </div>

  <div class="field">
    <%= form.label :min_rating %>
    <%= form.number_field :min_rating, id: :curriculum_min_rating %>
  </div>

  <div class="field">
    <%= form.label :max_rating %>
    <%= form.number_field :max_rating, id: :curriculum_max_rating %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :curriculum_description %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :curriculum_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/curriculums/edit.html.erb
<h1>Editing Curriculum</h1>

<%= render 'form', curriculum: @curriculum %>

<%= link_to 'Show', @curriculum %> |
<%= link_to 'Back', curriculums_path %>

app/views/curriculums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Curriculums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Min rating</th>
      <th>Max rating</th>
      <th>Description</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curriculums.each do |curriculum| %>
      <tr>
        <td><%= curriculum.name %></td>
        <td><%= curriculum.min_rating %></td>
        <td><%= curriculum.max_rating %></td>
        <td><%= curriculum.description %></td>
        <td><%= curriculum.active %></td>
        <td><%= link_to 'Show', curriculum %></td>
        <td><%= link_to 'Edit', edit_curriculum_path(curriculum) %></td>
        <td><%= link_to 'Destroy', curriculum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curriculum', new_curriculum_path %>

app/views/curriculums/new.html.erb
<h1>New Curriculum</h1>

<%= render 'form', curriculum: @curriculum %>

<%= link_to 'Back', curriculums_path %>

app/views/curriculums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @curriculum.name %>
</p>

<p>
  <strong>Min rating:</strong>
  <%= @curriculum.min_rating %>
</p>

<p>
  <strong>Max rating:</strong>
  <%= @curriculum.max_rating %>
</p>

<p>
  <strong>Description:</strong>
  <%= @curriculum.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @curriculum.active %>
</p>

<%= link_to 'Edit', edit_curriculum_path(@curriculum) %> |
<%= link_to 'Back', curriculums_path %>