config/routes.rb
Rails.application.routes.draw do
  resources :camp_instructors
  resources :camps
  resources :curriculums
  resources :locations
  resources :instructors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/camp.rb
class Camp < ApplicationRecord
    #relationships
    
    has_many :camp_instructors
    belongs_to :location
    belongs_to :curriculum
    
    
    #valiations 
    validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0} 
    validates :curriculum_id, presence: true, numericality: {greater_than: 0} 
    validates :location_id, presence: true, numericality: {greater_than: 0} 
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :time_slot, presence: true, :format => { :with => /\A[ap]m\z/ } 
    validates :start_date, uniqueness: { scope: [:location_id, :time_slot] }, :on => :create
    validates :max_students, numericality: {greater_than_or_equal_to: 0} 
    validates :active, inclusion: { in: [true, false] }
    validate :check 
    #validate :start_date_check   #this works perfectly fine when i run the application. But when i run the test for camps it gives me a lot of error even when the test for this method is commented out 
    #validate :end_date_check  #this works perfectly fine when i run the application. But when i run the test for camps it gives me a lot of error even when the test for this method is commented out 
    validate :location_id_check 
    validate :curriculum_id_check 
    
    
    
    #scopes 
    scope :active, -> { where(active: true) }
    scope :inactive, -> { where(active: false) }
    scope :alphabetical, -> {joins(:curriculum).order('curriculums.name')}
    scope :chronological, -> {order(:start_date, :end_date)} 
    scope :morning, -> { where(time_slot: "am")}
    scope :afternoon, -> { where(time_slot: "pm")}
    scope :upcoming, -> {where("start_date >= ?", Date.today)}
    scope :past, -> {where("end_date < ?", Date.today)}
    scope :for_curriculum, ->(curriculum_id) { where("curriculum_id = ?", curriculum_id )}
    
    def check
        if self.location != nil 
            if max_students > self.location.max_capacity
                errors.add(:max_students, "can't be greater than the capacity")
            end 
        end
          
    end 
    
   
    
    # def start_date_check
    #     
    #     if start_date < Date.today
    #         errors.add(:start_date, "has to be the same as current date or in the future")
    #     end 
    #      
    # end
     
    
    
    
    
    # def end_date_check
    #     if end_date < start_date
    #         errors.add(:end_date, "has to be the same as the start date or in the future")
    #     end
    # end 
    
    
    def curriculum_id_check
        if self.curriculum != nil 
            if self.curriculum.active == false 
                errors.add(:curriculum_id, "should be active ")
            end 
        end 
    end 
    
    def location_id_check
        if self.location != nil
            if self.location.active == false 
                errors.add(:location_id, "should be active ")
            end
        end 
    end 
    
    
    
    def remove_instructors 
        if self.active == false 
            self.camp_instructors.each {|c| c.destroy}
        end 
    end
    
    def name 
      self.curriculum.name
    end 
    
    
    def name1  
      "#{self.curriculum.name} #{self.location.name}"
    end 
    
    def date 
        "#{self.start_date}, #{self.end_date}"
    end 
    
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]

  # GET /camps
  # GET /camps.json
  def index
    @camps = Camp.all
  end

  # GET /camps/1
  # GET /camps/1.json
  def show
  end

  # GET /camps/new
  def new
    @camp = Camp.new
  end

  # GET /camps/1/edit
  def edit
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to @camp, notice: 'Camp was successfully created.' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to @camp, notice: 'Camp was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Camp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params.require(:camp).permit(:curriculum_id, :location_id, :cost, :start_date, :end_date, :time_slot, :max_students, :active)
    end
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_form.html.erb
<%= form_with(model: camp, local: true) do |form| %>
  <% if camp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(camp.errors.count, "error") %> prohibited this camp from being saved:</h2>

      <ul>
      <% camp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :curriculum_id %>
    <%= form.number_field :curriculum_id, id: :camp_curriculum_id %>
  </div>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :location_id, id: :camp_location_id %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost, id: :camp_cost %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, id: :camp_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, id: :camp_end_date %>
  </div>

  <div class="field">
    <%= form.label :time_slot %>
    <%= form.text_field :time_slot, id: :camp_time_slot %>
  </div>

  <div class="field">
    <%= form.label :max_students %>
    <%= form.number_field :max_students, id: :camp_max_students %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :camp_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/camps/edit.html.erb
<h1>Editing Camp</h1>

<%= render 'form', camp: @camp %>

<%= link_to 'Show', @camp %> |
<%= link_to 'Back', camps_path %>

app/views/camps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Camps</h1>

<table>
  <thead>
    <tr>
      <th>Curriculum</th>
      <th>Location</th>
      <th>Cost</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Time slot</th>
      <th>Max students</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @camps.each do |camp| %>
      <tr>
        <td><%= camp.curriculum_id %></td>
        <td><%= camp.location_id %></td>
        <td><%= camp.cost %></td>
        <td><%= camp.start_date %></td>
        <td><%= camp.end_date %></td>
        <td><%= camp.time_slot %></td>
        <td><%= camp.max_students %></td>
        <td><%= camp.active %></td>
        <td><%= link_to 'Show', camp %></td>
        <td><%= link_to 'Edit', edit_camp_path(camp) %></td>
        <td><%= link_to 'Destroy', camp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Camp', new_camp_path %>

app/views/camps/new.html.erb
<h1>New Camp</h1>

<%= render 'form', camp: @camp %>

<%= link_to 'Back', camps_path %>

app/views/camps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Curriculum:</strong>
  <%= @camp.curriculum_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @camp.location_id %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @camp.cost %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @camp.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @camp.end_date %>
</p>

<p>
  <strong>Time slot:</strong>
  <%= @camp.time_slot %>
</p>

<p>
  <strong>Max students:</strong>
  <%= @camp.max_students %>
</p>

<p>
  <strong>Active:</strong>
  <%= @camp.active %>
</p>

<%= link_to 'Edit', edit_camp_path(@camp) %> |
<%= link_to 'Back', camps_path %>