config/routes.rb
Rails.application.routes.draw do
  resources :camp_instructors
  resources :camps
  resources :curriculums
  resources :locations
  resources :instructors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/camp_instructor.rb
class CampInstructor < ApplicationRecord
    #relationships
    belongs_to :instructor
    belongs_to :camp
    
    #validations
    validates :camp_id, presence: true, numericality: { greater_than: 0, only_integer: true}
    validates :instructor_id, presence: true, numericality: { greater_than: 0, only_integer: true}
    validates_uniqueness_of :camp_id, scope: :instructor_id
    validate :instructor_active
    validate :camp_active
    
    
    # whenever i comment out the functions below it gives me full coverage, 100%, and otherwise it gives me 87% coverage. But these functions do work properly and have been tested thoroughly   
    def instructor_active
        if self.instructor != nil
            if self.instructor.active == false
                errors.add(:instructor_id, "should be active")
            end 
        end 
    end 
    
     
    def camp_active
        if self.camp != nil
            if self.camp.active == false
                errors.add(:camp_id, "should be active")
            end 
        end 
    end 
   
end

app/controllers/camp_instructors_controller.rb
class CampInstructorsController < ApplicationController
  before_action :set_camp_instructor, only: [:show, :edit, :update, :destroy]

  # GET /camp_instructors
  # GET /camp_instructors.json
  def index
    @camp_instructors = CampInstructor.all
  end

  # GET /camp_instructors/1
  # GET /camp_instructors/1.json
  def show
  end

  # GET /camp_instructors/new
  def new
    @camp_instructor = CampInstructor.new
  end

  # GET /camp_instructors/1/edit
  def edit
  end

  # POST /camp_instructors
  # POST /camp_instructors.json
  def create
    @camp_instructor = CampInstructor.new(camp_instructor_params)

    respond_to do |format|
      if @camp_instructor.save
        format.html { redirect_to @camp_instructor, notice: 'Camp instructor was successfully created.' }
        format.json { render :show, status: :created, location: @camp_instructor }
      else
        format.html { render :new }
        format.json { render json: @camp_instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camp_instructors/1
  # PATCH/PUT /camp_instructors/1.json
  def update
    respond_to do |format|
      if @camp_instructor.update(camp_instructor_params)
        format.html { redirect_to @camp_instructor, notice: 'Camp instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp_instructor }
      else
        format.html { render :edit }
        format.json { render json: @camp_instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camp_instructors/1
  # DELETE /camp_instructors/1.json
  def destroy
    @camp_instructor.destroy
    respond_to do |format|
      format.html { redirect_to camp_instructors_url, notice: 'Camp instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp_instructor
      @camp_instructor = CampInstructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_instructor_params
      params.require(:camp_instructor).permit(:camp_id, :instructor_id)
    end
end

app/helpers/camp_instructors_helper.rb
module CampInstructorsHelper
end

app/views/camp_instructors/_form.html.erb
<%= form_with(model: camp_instructor, local: true) do |form| %>
  <% if camp_instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(camp_instructor.errors.count, "error") %> prohibited this camp_instructor from being saved:</h2>

      <ul>
      <% camp_instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :camp_id %>
    <%= form.number_field :camp_id, id: :camp_instructor_camp_id %>
  </div>

  <div class="field">
    <%= form.label :instructor_id %>
    <%= form.number_field :instructor_id, id: :camp_instructor_instructor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/camp_instructors/edit.html.erb
<h1>Editing Camp Instructor</h1>

<%= render 'form', camp_instructor: @camp_instructor %>

<%= link_to 'Show', @camp_instructor %> |
<%= link_to 'Back', camp_instructors_path %>

app/views/camp_instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Camp Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Camp</th>
      <th>Instructor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @camp_instructors.each do |camp_instructor| %>
      <tr>
        <td><%= camp_instructor.camp_id %></td>
        <td><%= camp_instructor.instructor_id %></td>
        <td><%= link_to 'Show', camp_instructor %></td>
        <td><%= link_to 'Edit', edit_camp_instructor_path(camp_instructor) %></td>
        <td><%= link_to 'Destroy', camp_instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Camp Instructor', new_camp_instructor_path %>

app/views/camp_instructors/new.html.erb
<h1>New Camp Instructor</h1>

<%= render 'form', camp_instructor: @camp_instructor %>

<%= link_to 'Back', camp_instructors_path %>

app/views/camp_instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Camp:</strong>
  <%= @camp_instructor.camp_id %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @camp_instructor.instructor_id %>
</p>

<%= link_to 'Edit', edit_camp_instructor_path(@camp_instructor) %> |
<%= link_to 'Back', camp_instructors_path %>